export const environment = {
  production: true,
  apiUrl: 'https://app-back.kuailiandp.com',
  projectApiUrl: 'https://app-back.kuailiandp.com',
  kuailianBankUrl: 'https://bank.crosschange.exchange',
  // kuailianAcademyUrl: 'https://kuailianacademy.com',
  kuailianAcademyUrl: 'https://academy.kuailiandp.com/',
  kuailianLandingPageUrl: 'https://kuailiandp.com',
  kuailianMarketplaceUrl: 'https://market.kuailiandp.com',
  kuailianPurposeUrl: 'https://purpose.kuailiandp.com',
  zendeskUrl: 'https://kuailian.zendesk.com/',
  recaptchaKey: '6Lfx0rEUAAAAAOSq-RTDC2xjEimUytQDKkffrPm3',
  centrifugeUrl: 'wss://websocket.kuailiandp.com',
  poolMonitoringUrl: 'https://mn.kuailiandp.com',
  realTimeMonitoringUrl: 'https://pool.kuailiandp.com',
  locales: ['en', 'ru', 'es', 'de', 'uk', 'chi'],
  defaultLocale: 'en',
  filesHashStamp: new Date().getTime(),
  kuailianPlatformUrl: '',
  refreshUrl: '',
  assetsAuth: ''
};
