export const environment = {
  production: true,
  apiUrl: 'https://stage-app-back.kuailiandp.net',
  projectApiUrl: 'https://stage-app-back.kuailiandp.net',
  kuailianBankUrl: 'https://stage-crosschange.kuailiandp.net',
  kuailianAcademyUrl: 'https://stage-academy.kuailiandp.net',
  kuailianLandingPageUrl: 'https://stage.kuailiandp.net',
  kuailianMarketplaceUrl: 'https://stage-market.kuailiandp.net',
  kuailianPurposeUrl: 'https://stage-purpose.kuailiandp.net',
  zendeskUrl: 'https://kuailian.zendesk.com/',
  recaptchaKey: '6LdfE5gUAAAAANkTBbWl1FHLVjQBoQeBiWu8QIjV',
  centrifugeUrl: 'wss://stage-websocket.kuailiandp.net',
  poolMonitoringUrl: 'https://54.171.253.238/',
  realTimeMonitoringUrl: 'https://stage-pool.kuailiandp.net',
  locales: ['en', 'ru', 'es', 'de', 'uk', 'chi'],
  defaultLocale: 'en',
  filesHashStamp: new Date().getTime(),
  kuailianPlatformUrl: '',
  refreshUrl: '',
};
